id: I8C814D7E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T14:16:07+00:00'
last_modified: '2022-06-08T13:06:21.192049+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN3417
  title: གསུང་འབུམ། རེད་མདའ་བ་གཞོན་ནུ་བློ་གྲོས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    8B6D:
      image_group_id: I3CN4496
      title: ''
      total_pages: 310
      order: 1
      base_file: 8B6D.txt
    '7932':
      image_group_id: I3CN4497
      title: ''
      total_pages: 794
      order: 2
      base_file: 7932.txt
    BF11:
      image_group_id: I3CN4498
      title: ''
      total_pages: 614
      order: 3
      base_file: BF11.txt
    CCDC:
      image_group_id: I3CN4499
      title: ''
      total_pages: 456
      order: 4
      base_file: CCDC.txt
    EAA6:
      image_group_id: I3CN4500
      title: ''
      total_pages: 502
      order: 5
      base_file: EAA6.txt
    76D5:
      image_group_id: I3CN4501
      title: ''
      total_pages: 360
      order: 6
      base_file: 76D5.txt
    D309:
      image_group_id: I3CN4502
      title: ''
      total_pages: 592
      order: 7
      base_file: D309.txt
    BFD3:
      image_group_id: I3CN4503
      title: ''
      total_pages: 486
      order: 8
      base_file: BFD3.txt
    A8FB:
      image_group_id: I3CN4504
      title: ''
      total_pages: 642
      order: 9
      base_file: A8FB.txt
    FBF1:
      image_group_id: I3CN4505
      title: ''
      total_pages: 580
      order: 10
      base_file: FBF1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
